export const countryFlags: Record<string, any> = {
  'ALEMANIA': require('../../assets/flags/Alemania.png'),
  'ARGENTINA': require('../../assets/flags/Argentina.png'),
  'AUSTRALIA': require('../../assets/flags/Australia.png'),
  'BRASIL': require('../../assets/flags/Brazil.png'),
  'COLOMBIA': require('../../assets/flags/Colombia.png'),
  'ESPAÑA': require('../../assets/flags/Espana.png'),
  'FINLANDIA': require('../../assets/flags/Finlandia.png'),
  'FRANCIA': require('../../assets/flags/Francia.png'),
  'INDONESIA': require('../../assets/flags/Indonesia.png'),
  'IRLANDA': require('../../assets/flags/Irlanda.png'),
  'ITALIA': require('../../assets/flags/Italia.png'),
  'JAPÓN': require('../../assets/flags/Japon.png'),
  'JAPON': require('../../assets/flags/Japon.png'), // Sin tilde por si acaso
  'PORTUGAL': require('../../assets/flags/Portugal.png'),
  'REINO UNIDO': require('../../assets/flags/ReinoUnido.png'),
  'REPÚBLICA CHECA': require('../../assets/flags/RepublicaCheca.png'),
  'REPUBLICA CHECA': require('../../assets/flags/RepublicaCheca.png'),
  'SUDÁFRICA': require('../../assets/flags/Sudafrica.png'), 
  'SUDAFRICA': require('../../assets/flags/Sudafrica.png'), 
  'TAILANDIA': require('../../assets/flags/Tailandia.png'),
  'TURQUÍA': require('../../assets/flags/Turquia.png'),
  'TURQUIA': require('../../assets/flags/Turquia.png'),
  'ESTADOS UNIDOS': require('../../assets/flags/USA.png'),
  'USA': require('../../assets/flags/USA.png'),
  'AUSTRIA': require('../../assets/flags/Austria.png'),
  'HUNGRÍA': require('../../assets/flags/Hungria.png'),
  'HUNGRIA': require('../../assets/flags/Hungria.png'),
  'INDIA': require('../../assets/flags/India.png'),
  'MALASIA': require('../../assets/flags/Malasia.png'),
  'PAÍSES BAJOS': require('../../assets/flags/PaisesBajos.png'),
  'PAISES BAJOS': require('../../assets/flags/PaisesBajos.png'),
  'QATAR': require('../../assets/flags/Qatar.png'),
  'SAN MARINO': require('../../assets/flags/SanMarino.png'),

  'CHANG INTERNATIONAL CIRCUIT': require('../../assets/flags/Tailandia.png'),
  'AUTÓDROMO INTERNACIONAL AYRTON SENNA': require('../../assets/flags/Brazil.png'),
  'AUTODROMO INTERNACIONAL AYRTON SENNA': require('../../assets/flags/Brazil.png'),
  'CIRCUIT OF THE AMERICAS (COTA)': require('../../assets/flags/USA.png'),
  'CIRCUITO DE JEREZ - ÁNGEL NIETO': require('../../assets/flags/Espana.png'),
  'CIRCUITO DE JEREZ - ANGEL NIETO': require('../../assets/flags/Espana.png'),
  'LE MANS - BUGATTI CIRCUIT': require('../../assets/flags/Francia.png'),
  'CIRCUIT DE BARCELONA-CATALUNYA': require('../../assets/flags/Espana.png'),
  'AUTODROMO INTERNAZIONALE DEL MUGELLO': require('../../assets/flags/Italia.png'),
  'BALATON PARK CIRCUIT': require('../../assets/flags/Hungria.png'),
  'AUTOMOTODROM BRNO': require('../../assets/flags/RepublicaCheca.png'),
  'TT CIRCUIT ASSEN': require('../../assets/flags/PaisesBajos.png'),
  'SACHSENRING': require('../../assets/flags/Alemania.png'),
  'SILVERSTONE CIRCUIT': require('../../assets/flags/ReinoUnido.png'),
  'MOTORLAND ARAGÓN': require('../../assets/flags/Espana.png'),
  'MOTORLAND ARAGON': require('../../assets/flags/Espana.png'),
  'MISANO WORLD CIRCUIT MARCO SIMONCELLI': require('../../assets/flags/SanMarino.png'),
  'RED BULL RING': require('../../assets/flags/Austria.png'),
  'MOBILITY RESORT MOTEGI': require('../../assets/flags/Japon.png'),
  'PERTAMINA MANDALIKA CIRCUIT': require('../../assets/flags/Indonesia.png'),
  'PHILLIP ISLAND CIRCUIT': require('../../assets/flags/Australia.png'),
  'SEPANG INTERNATIONAL CIRCUIT': require('../../assets/flags/Malasia.png'),
  'LUSAIL INTERNATIONAL CIRCUIT': require('../../assets/flags/Qatar.png'),
  'AUTÓDROMO INTERNACIONAL DO ALGARVE': require('../../assets/flags/Portugal.png'),
  'AUTODROMO INTERNACIONAL DO ALGARVE': require('../../assets/flags/Portugal.png'),
  'CIRCUIT RICARDO TORMO': require('../../assets/flags/Espana.png'),
  'AUTÓDROMO TERMAS DE RÍO HONDO': require('../../assets/flags/Argentina.png'),
  'AUTODROMO TERMAS DE RIO HONDO': require('../../assets/flags/Argentina.png'),
  'GRAN PREMIO SOLIDARIO DE BARCELONA': require('../../assets/flags/Espana.png'),
  'BUDDH INTERNATIONAL CIRCUIT': require('../../assets/flags/India.png'),
  'GRAN PREMIO DE ESTIRIA': require('../../assets/flags/Austria.png'),
  'GRAN PREMIO DEL ALGARVE': require('../../assets/flags/Portugal.png'),
  'GRAN PREMIO DE ANDALUCÍA': require('../../assets/flags/Espana.png'),
  'GRAN PREMIO DE ANDALUCIA': require('../../assets/flags/Espana.png'),
  'GRAN PREMIO DE EMILIA-ROMAÑA': require('../../assets/flags/Italia.png'),
  'GRAN PREMIO DE EMILIA-ROMANA': require('../../assets/flags/Italia.png'),
  'GRAN PREMIO DE EUROPA': require('../../assets/flags/Espana.png'),
  'INDIANAPOLIS MOTOR SPEEDWAY': require('../../assets/flags/USA.png'),
};

export const getFlag = (searchString: string) => {
  if (!searchString) return require('../../assets/flags/Default.png');
  
  //Limpiamos el texto, lo pasamos a mayúsculas y quitamos espacios extra
  const cleanString = searchString.trim().toUpperCase();
  
  //Si encuentra la bandera te la da, si no, te da la imagen por defecto
  return countryFlags[cleanString] || require('../../assets/flags/Default.png'); 
};